apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-landing
  namespace: web
spec:
  secretName: home-landing-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.global.homeDomain }}
    - www.{{ .Values.global.homeDomain }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hobby-landing
  namespace: web
spec:
  secretName: hobby-landing-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.global.hobbyDomain }}
    - www.{{ .Values.global.hobbyDomain }}
