apiVersion: v2
name: sealed-secrets
version: 1.0.0
description: Sealed Secrets controller and web UI
dependencies:
  - name: sealed-secrets
    version: "2.*"
    repository: "https://bitnami-labs.github.io/sealed-secrets"
