---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-ui
  namespace: sealed-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sealed-secrets-ui
  template:
    metadata:
      labels:
        app: sealed-secrets-ui
    spec:
      containers:
        - name: sealed-secrets-ui
          image: docker.io/alpheya/sealed-secrets-ui:0.3.3
          ports:
            - containerPort: 8080
          env:
            - name: SEALED_SECRETS_CONTROLLER_NAME
              value: sealed-secrets-controller
            - name: SEALED_SECRETS_CONTROLLER_NAMESPACE
              value: sealed-secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets-ui
  namespace: sealed-secrets
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: sealed-secrets-ui
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sealed-secrets-ui
  namespace: sealed-secrets
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - secrets.home.{{ .Values.global.homeDomain }}
  rules:
    - host: secrets.home.{{ .Values.global.homeDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sealed-secrets-ui
                port:
                  number: 80
