$ANSIBLE_VAULT;1.1;AES256
66313830303165616134363165613634653930343864346133323335386265393332303631363065
6333633235333934636563666464336330343535353331380a643435366362613534613162633735
64306535393336353930383133393631616634636265393937616565383361373537643231353639
6366343863663861300a643162373336623232613935653961353264376338333336626561656538
62643261623166383566633439323366663864333830656336643734353036633466616439653838
32343931373566383333306539323866333963646131343931333066613361323963363839373261
37643564653366646632336534383962326566316131626339396134326232313530393864323134
35386132363530626633383661343336373738653762663561373138393239653531343338326265
65643262356331383738656361323035376536643563383137333236343739316338613132353739
6438626431636634363661303664643637343334643464303630
