apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zot
  namespace: registry
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - registry.home.{{ .Values.global.homeDomain }}
  rules:
    - host: registry.home.{{ .Values.global.homeDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zot
                port:
                  number: 5000
