apiVersion: v2
name: prometheus
version: 1.0.0
description: Prometheus monitoring
dependencies:
  - name: prometheus
    version: "27.*"
    repository: "https://prometheus-community.github.io/helm-charts"
