apiVersion: v2
name: prometheus
version: 1.0.0
description: Prometheus and Grafana monitoring stack
dependencies:
  - name: kube-prometheus-stack
    version: "80.*"
    repository: "https://prometheus-community.github.io/helm-charts"
