all:
  children:
    k3s_cluster:
      children:
        control_plane:
          hosts:
            main-server:
              ansible_host: localhost
              ansible_connection: local
              k3s_role: server
        workers:
          hosts:
            kvatch:
              ansible_host: 192.168.2.200
              ansible_user: shy
              k3s_role: agent
              k3s_server_ip: 192.168.2.100
              k3s_system_reserved_memory: 34Gi
    game_servers:
      hosts:
        kvatch:
          ansible_host: 192.168.2.200
          ansible_user: shy
  vars:
    ansible_python_interpreter: /usr/bin/python3

    # k3s config
    k3s_version: v1.32.11+k3s1
    k3s_cluster_cidr: 10.42.0.0/16
    k3s_service_cidr: 10.43.0.0/16
