apiVersion: v1
kind: Endpoints
metadata:
  name: pelican
subsets:
  - addresses:
      - ip: {{ .Values.gameserverIP }}
    ports:
      - name: http
        port: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pelican-wings
subsets:
  - addresses:
      - ip: {{ .Values.gameserverIP }}
    ports:
      - name: http
        port: 8080
