apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pelican
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - pelican.home.{{ .Values.global.homeDomain }}
  rules:
    - host: pelican.home.{{ .Values.global.homeDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pelican
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pelican-wings
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - wings.home.{{ .Values.global.homeDomain }}
  rules:
    - host: wings.home.{{ .Values.global.homeDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pelican-wings
                port:
                  number: 8080
