---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: comet-secrets
  namespace: media
spec:
  encryptedData:
    admin-password: AgCQuV6RuCaQWGL+BQkzGpD94bZnYhPLDt/d9fvXnKuDQqns40RL1kjHFdoLl3t8PCGETAR/gM82Xf+RoiYWIImNdiq1fUxalg5Fu8pq8LfemPBsUii8aAtLX6403Z3pEvMoD12Hq1AUIIuM474Vl87gHU/j2wM0lAFwOigqSW7tvFI0GJDIXt4NmYZp9guPc9HyX7Z3eXPdy6P1M/NhbX9chjkUHIUGlQuHtI1aTWAzrFL1b+TpCq/AG8XzoyU302nHM8Jwsc6wNkOtaurLeDdrwlX+axAoPp95gE+Q2FvXnYLn/OM34srXZN4LKQns3qyfZGfHw8ql28IZ93xD4m9J49/A7a/cHA0Nb32FZjJm8VAvDB8dRIy+Ul8Y7lZvI27TDiGqbFSoLf9/GFkDwwNoBaYWN7ACw0nGtvgUWeE9qv/tq74wS2ngf7R0/F65XXkDMWwI/2J6LBTBmCfQk85T5qzUJc0dkBTpLVOZJe5OGYGAILDIwWRaCyzJfGfJXflLbiV/x390zwE1GHb9J41wCkVJzDzOw+eGuMKt6JXvzFpn/QQThkQ3Kv7orJJMr+enRoFtZ0DdpRrGb4JeZ5dXBjPWztaogkpyMRPpbLi13wOrBJl6es5Fk+k9Q2rGOfJ6Hr3G3AhrtfUHZqbxqexaTsoP+y7mh7xPrZ9aIt1Ndqei2WU8+LsvLFQdZGjZW4ldhmRDvhYUmpZz
    proxy-password: AgBJb04WL2W+MPNM8KCOjo8j11dlYstTXVHQYOUzNHL17rIYzErrKLmsl5l8lD4Vh8+5XN2KM6NuTz1kUU8xWl6hkr2TnnJzxw0SEG+4Hf69m0nzYLZ84Ze1m72wpE9kMpdrVdnROyxYizfcXQCxy0UEn/LIQyC0FUZR+fNjrbGRHh6szulV1k0xKMxld/UCUPQ9xgasAUOW3xA6M1jIZxUpihmfsb8ZdIBiTdn3i4/RKiP1cu9Bg4ex+IVlzYjavleGK6MOtk388XKLYcFdCbgfM07JaL3KIBQMdDTuVHKlBwVdLe3m/H/v6dM1pz3HgEquKRaJhcFY8vcB5DEhE0dX9ENRbZh+Lg10AcPKFccewXjDhtHX8C2AQ7TKwX5+rQIresnjKwE9FB9oCkZF5QTwSscLkKb7bFN1eK5Il6Hb2J9+XZVOKKzP+H/XCL307jiL89iWNbKsHCzuxyydIdrgrT0Cf5Is4o1KKO/1nvwka20m7g8L/BtwIK7HrPZlDbrn/TmmSBU3AorYVs3z2u9zskpyUbB0+LMMdKOyKa2UEYF+bSqHs+9Xw7Ty0F0WcqsIseEFkNtcT2R8iG06aY84/E9s2D2xTiUcJ5xTPhQHktKWD1xqcR3lZNphjwQNMNLyvPuUOdAtSrFIRaGkdBZuX4H3ApFYdfunvrwn7bA1A5w7fzwOPxWpfv+OBV58DhX/89rae2OG+hKggg==
  template:
    metadata:
      name: comet-secrets
      namespace: media
