apiVersion: v2
name: cert-manager
version: 1.0.0
description: cert-manager certificate management
dependencies:
  - name: cert-manager
    version: "v1.*"
    repository: "https://charts.jetstack.io"
