---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare
spec:
  encryptedData:
    token: AgBS+UjbBWrUpNLh9dXW0vrxZGGquHvayJdLXan+C8nRJg7gbeOVqqMZJs3jrnjfeveipI1IwJh9VzXxXYhMMj9lkPdNBAHM7H/jXLVJHuZEgJ5arLxKeDdBVnYkxN9p7UglL7OuWGnDr7AliIOnth2mioYRKCHli77o2h5+5XmqD5Zebpjz/ap77hpPJMbweVD85HaOoK6nMeO0RTt9JHLDq2X4bCzrogq7DH+CDJufWDDM2FD6Ju3RxMLShliSKGfmGGHPm3iSOtyVUUxlJNycBs8uJWMvcB1CzKpw5sXfna0ctGh8ZH0e5vr6X/sruNiuJAr7wCbcq1wwbG0Zxp9lbKHyeVaZuQ2u8/eCiwF5pC9yBJlyCyM0MC9WaNX/PIyVsJkw+CapvQkjGetvbCShbnNPORr96tl7JLoX94ZLd5d55W1LKpiNN/adzvKgj7gY+4dRnLPlelH6efHQnYhxwXHdUqOCl5T+u8lBwi1jtqEtLO/ZjoIE3gJ5ROiBx7Gvbu33mvB3UDLZBXB0nUch8XPYgkStnTBRSMkAebh6xjJeYgvjPX2jOJrjG18XDfRDSzisM/XpjzNiNKGsLed7vvGYsuhnSKBdFd1ps1U2CWSi6Qewq/imYOlw1DXewI275D0PXMmSY/fF6uhKfrOUUsZx8lv63BmpfkWPVvKoH6DtI2YiszLHKyg8lCS/bXU2uteSl444HjhO7ZWM/Pv8gf/OItpOuwfAkPXbTzqnwCWtw09Jy4Fw9mAkL/2DrtzfLS6fVTwoBEdV7GDYa9XxMBF023dklzJUIoCtkKmxWritQCRCC5jzK+Ap0SoVhHcM5/wvGAu2Z1Gw/gtKnBJkbnM72tqwAcTaeuW1C4F3pPLu1A6gTPgfsB/+yD8I5iyD4j4EOxhktOKFaKSYHieo+oQFVKCSpm/zDiV+7gJR30vtjlY=
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare
