---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    token: AgCP9Ga/bxdZ8cQtxgRJIUynMpNfuepUxr8jHmHHws0dP89ckcmnk0wxJlHseGlyOKJvFUmqoikJr7bQYmM/XRYyibdRLyju5i8QVUQNcSDmrS1o4sYcRZ2qOiFeajwbyLGPZSjBumyvZo6O2zOPhhQsolJkhuVkbGReGJYfHUgnXfytY0uwNAlP7TRh03tgLbD71po+gy1Q5lsY5x+zexYYk3PEKc9WHTi12YXGwJFltfu4SC0jRgHzIB6bvNgJOnofY1XgFXh3FLza7GXXq2vAuNPaohw248BBwdBSPV5xI+PlyolhQTaQDbZ85NJBf/fix4ODqyLfb14KlkbNyhrNNGaideQNmA/UGXP5u7FQbW0n/S32fZPP5KtjH95n5ueoNKzmu4qgMTX2hmCuOGnZK2ONTcvdU1NiZFLDRMPMPcQDWvZmps/z0m3zrAaF066OA46ueFNaRXzYArl3I3S9qwP+4DIZwPu3eAWkqPL3QmuGsR9pPxqbMOFp8T++yJtzMJu7F0O6xvzGPPNCH7F4nA0wTtyGFTXG9EkuISJoqlKwtFH3gPYuHJMyxpnGY9e3lJ8Hn1ssGLEiw9w51jEMbHJR97u8JCsqFRCmivHMGaz+s6KNNxjsCn1Jgtv2Ez1gelbK+MA4mHpN7UUKuj2qTRaec9JaCOEcUHB1Enmq9igISSRMEZ2DMA/8gLAN2toVHSPUNJ7UWzQ+xztAgp35LuIsAVJXVa1EmdUvjJRAPRzWxpSLNAnTK4PAUL7eZiGnG5YgLXu5SxY5VB1Zwz4ESzQpdKMSiav8B8Se4pxwYrlLpTp7Rm8wZWGTaw/lZlRUYvTrTE5bm08Gbt8MBwyKpAN4Ppxl08P/Lx9rqu4B/K6qdLpIl9+CSY+p6bdhYnqWCQ8O9eEK7OeUDRpQc7QC+Oi2FN2WLbQ4nlmlRfl1HY7o+kg=
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare-tunnel
